apps/products/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView
from products.models import Product

urlpatterns = patterns('products.views',
    url(r'^list/$', ListView.as_view(
        template_name="products/list.html",
        model=Product), name='list'),
    url(r'^add/$', 'add_or_edit', name='add'),
    url(r'^edit/(?P<id>\d+)/$', 'add_or_edit', name='edit'),
    url(r'^remove/(?P<id>\d+)/$', 'remove', name='remove'),
)

django_products_crud/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_products_crud.views.home', name='home'),
    # url(r'^django_products_crud/', include('django_products_crud.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^products/', include('products.urls', namespace='products')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT})
    )

apps/products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255)
    details = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def __unicode__(self):
        # preferred string formatting, look at: PEP-3101
        data = {'name': self.name, 'details': self.details}
        return u'Name: {name}; Details: {details}'.format(**data)

apps/products/forms.py
from django.forms import ModelForm
from products.models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product

apps/products/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages

from products.forms import ProductForm
from products.models import Product

def add(request):
    if request.POST:
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()

            # If the save was successful, redirect to another page
            redirect_url = reverse('products:list')
            return HttpResponseRedirect(redirect_url)
    else:
        form = ProductForm()

    content = {'title': 'Add new product', 'form': form}
    context_instance = RequestContext(request)
    return render_to_response('products/form.html', content, context_instance)


# look at: http://stackoverflow.com/questions/1854237/django-edit-form-based-on-add-form
def add_or_edit(request, id=None):
    if id:
        product = get_object_or_404(Product, pk=id)
        action = "Edit "
    else:
        product = Product()
        action = "Add a new "

    if request.POST:
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()

            # If the save was successful, redirect to another page
            redirect_url = reverse('products:list')
            return HttpResponseRedirect(redirect_url)
    else:
        form = ProductForm(instance=product)

    content = {'title': action + 'product', 'form': form}
    context_instance = RequestContext(request)
    return render_to_response('products/form.html', content, context_instance)


def remove(request, id=None):
    # TODO: not implemented yet, redirect to list
    # messages.add_message(request, messages.SUCCESS, "The item was succesfuly removed")
    messages.add_message(request, messages.WARNING, "This functionality it's not implemented yet.")
    redirect_url = reverse('products:list')
    return HttpResponseRedirect(redirect_url)

apps/products/templates/products/form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}{{ title }}{% endblock %}

{% block header %}
  <h2>{{ title }}</h2>
{% endblock %}

{% block content %}

  <form class="form-horizontal" action="." method="POST"> 
    {% csrf_token %}

    <fieldset>
      {% for field in form %}
        <div class="control-group{% if field.errors %} error{% endif %}">
          <label class="control-label">{{ field.label }} {% if field.field.required %}(*){% endif %}</label>
          <div class="controls">
            {{ field|add_class:"input-xlarge" }}
            <p class="help-block">{{ field.help_text }}</p>
          </div>
        </div>
      {% endfor %}

      <div class="form-actions">
        <input type="submit" class="btn btn-primary" value="Save">
        <a class='btn btn-inverse' href="{% url 'products:list' %}">Cancel</a>
      </div>
    </fieldset>
  </form>
{% endblock %}

apps/products/templates/products/list.html
{% extends "base.html" %}

{% block title %}Products List{% endblock %}

{% block header %}
  <h2>Products List</h2>
{% endblock %}

{% block content %}

  <table class="table table-striped table-bordered products-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Details</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
  {% for product in object_list %}
    <tr>
      <td>{{ product.name }}</td>
      <td>{{ product.details }}</td>
      <td>{{ product.price }}</td>
      <td>
        <a class='btn btn-primary btn-small' href="{% url 'products:edit' product.id %}">edit</a>
        <a class='btn btn-danger btn-small remove' href="{% url 'products:remove' product.id %}">delete</a>
      </td>
    </tr>
  {% endfor %}
  </table>

  <a class='btn btn-success' href="{% url 'products:add' %}">add new product</a>

{% endblock %}

{% block extra_scripts %}
  <script src="{{STATIC_URL}}bootbox.min.js"></script>
  <script type="text/javascript" charset="utf-8">
    $('.products-table').on('click', '.remove', function(event){
        event.preventDefault();
        var url = $(this).attr('href');

        bootbox.confirm('Are you sure to remove that item?', 'Cancel', 'Remove!', function(result){
          if (result) {
            window.location.href = url;
          }
        });
    });
  </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Products CRUD{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 41px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="{{STATIC_URL}}css/main.css">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% block extrahead %}
    {% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Django Products CRUD</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="{% url 'products:list' %}">Products list</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <header>
      <div class="container">
        {% block header %}
        {% endblock %}
      </div> 
    </header>

    <div id="messages" class="container">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{message.tags}}">
        <a class="close" data-dismiss="alert">×</a>
        {{message}}
      </div>
      {% endfor %}
      {% endif %}
    </div>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div> <!-- /container -->


    <footer>
      {% block footer %}
      {% endblock %}
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{STATIC_URL}}jquery-1.9.1.min.js"><\/script>')</script>

    <script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>

    <script src="{{STATIC_URL}}js/main.js"></script>

    {% block extra_scripts %}
    {% endblock %}
  </body>
</html>